
# Jobs for configuring Jenkins itself - Not application build jobs

- job:
    # TODO: rename to Jenkins_DSL
    name: Jenkins_UI_Views
    # TODO: Add url trigger
    description: |
        <p><b>Create all DSL defined Jenkins Views and Jobs</b></p>
    node: master
    properties:
      - github:
          url: https://github.com/devops-workflow/jenkins-dsls/
      - 'custom-icon':
          custom-icon: jenkins.png
      - sidebar:
          url: https://jenkinsci.github.io/job-dsl-plugin/
          text: DSL API Viewer
          icon: /userContent/customIcon/jenkins.png
      - sidebar:
          url: https://github.com/jenkinsci/job-dsl-plugin/wiki
          text: DSL Wiki
          icon: /userContent/customIcon/jenkins.png
    scm:
      - 'github':
          github-repo: jenkins-dsls
          github-url: https://github.com
          github-org: devops-workflow
    builders:
      - 'dsl-target':
          dsl-target: DSLs/views*.dsl
          # Change to 2 lines for 1 builder
      #- 'dsl-target':
      #    dsl-target: |
      #        DSLs/views*.dsl
      #        DSLs/jobs*.dsl
    triggers:
      - pollscm: 'H/15 * * * *'

- job:
    name: Jenkins_Job_Builder
    description: |
        Job to build all other jobs with Jenkins Job Builder
    node: master
    parameters:
      - string:
          name: remote_job_name
          default: "NO-JOB"
          description: "Jenkins job to get job build definition from"
      - choice:
          name: jjb_cache
          choices:
            - use
            - flush
          description: "Can use to flush cache"
      # Add node parameter. Must run on same node as job that called it
      #- label:
      #    name: node
      #    default: master
      #    description: "The node where the job will run"
    properties:
      - github:
          url: https://github.com/devops-workflow/jenkins-job-builder-config/
      - 'custom-icon':
          custom-icon: jenkins.png
      - sidebar:
          url: http://docs.openstack.org/infra/jenkins-job-builder/index.html
          text: JJB Documentaion
          icon: /userContent/customIcon/jenkins.png
    scm:
      - 'github':
          github-repo: jenkins-job-builder-config
          github-url: https://github.com
          github-org: devops-workflow
    builders:
      - syntax-bash:
      - shell: |
            ./run-jjb.sh $remote_job_name $jjb_cache
      # If job and jjb made changes, trigger calling job
      # 1) if job and find text in console log
      # 2) tee jjb output to file (jjb.log). Grep text in file
      #- conditional-step:
      #    condition-kind: and
      #    condition-operands:
      #        - condition-kind: not
      #          condition-operand:
      #              condition-kind: strings-match
      #              condition-string1: $remote_job_name
      #              condition-string2: "NO-JOB"
      #              condition-case-insensitive: false
      #        #- condition-kind: text-finder (not currently supported by JJB)
      #        - condition-kind: shell
      #          condition-command: "grep -E 'Number of jobs updated:\S+[1-9]' jjb.log"
      #          # Src line: INFO:root:Number of jobs updated: 0
      #    steps:
      #      - trigger-builds:
      #        - project:
      #            - $remote_job_name
      #          current-parameters: false
      #          # make sure it doesn't run jjb again
      #          predefined-parameters:
      #            remote_job_name=$JOB_NAME
      #          block: false
    publishers:
      - claim-build
      # Unknown issue with warnings
      #- warnings:
      #    console-log-parsers:
      #      - "Custom Bash Syntax"
    triggers:
      - pollscm: 'H/5 * * * *'

- job:
    name: Jenkins_Display_icons
    description: |
        Display all the available icons for use in jobs
    node: master
    properties:
      - github:
          url: https://github.com/devops-workflow/jenkins-display-icons/
      - 'custom-icon':
          custom-icon: jenkins.png
    scm:
      - 'github':
          github-repo: jenkins-display-icons
          github-url: https://github.com
          github-org: devops-workflow
    builders:
      - syntax-bash:
      - shell: ./generate-icons-page.sh
    publishers:
      - html-publisher:
          name: "Icons"
          dir: "."
          files: "icons.html"
    triggers:
      - 'files-found-folder':
          cron: "H * * * *"
          path: "$JENKINS_HOME/userContent/customIcon"
          include: "*.png"

# TODO: Enable once control of these is removed from puppet
# TODO: Move icons to new repo. As they will no longer be managed by puppet
#- job:
#    name: Jenkins_Update_icons
#    description: |
#        Update icons in Jenkins from Git repo
#    node: master
#    properties:
#      - github:
#          url: https://github.com/devops-workflow/puppet_module_site_workflow/tree/master/files/jenkins/images
#      - 'custom-icon':
#          custom-icon: jenkins.png
#    scm:
#      - 'github':
#          github-repo: puppet_module_site_workflow
#          github-url: https://github.com
#          github-org: devops-workflow
#    builders:
#      - shell:
#          !include-raw:
#            - ./global/scripts/update-icons.sh
#    publishers:
#      - trigger-parameterized-builds:
#          - project: Jenkins_Display_Icons
#            condition: 'SUCCESS'
#            trigger-with-no-params: True
#    triggers:
#      - pollscm: 'H/20 * * * *'

# name: Jenkins_Auto_Job_Builder
