
# Jobs for configuring Jenkins itself - Not application build jobs

- job:
    name: Jenkins_UI_Views
    # TODO: Add url trigger
    description: |
        <p><b>Create all defined Jenkins Views</b></p>
    properties:
      - github:
          url: https://github.com/devops-workflow/jenkins-dsls/
      - 'custom-icon':
          custom-icon: jenkins.png
    scm:
      - 'github':
          github-repo: jenkins-dsls
          github-url: https://github.com
          github-org: devops-workflow
    builders:
      - 'dsl-target':
          dsl-target: DSLs/views-*.dsl
    triggers:
      - pollscm: '*/15 * * * *'

- job:
    name: Jenkins_Job_Builder
    description: |
        Job to build all other jobs with Jenkins Job Builder
    parameters:
      - string:
          name: remote_job_name
          default: "NO-JOB"
          description: "Jenkins job to get job build definition from"
    properties:
      - github:
          url: https://github.com/devops-workflow/jenkins-job-builder-config/
      - 'custom-icon':
          custom-icon: jenkins.png
    scm:
      - 'github':
          github-repo: jenkins-job-builder-config
          github-url: https://github.com
          github-org: devops-workflow
    builders:
      - syntax-bash:
      - shell: |
            ./run-jjb.sh $remote_job_name
    publishers:
      - claim-build
      # Unknown issue with warnings
      #- warnings:
      #    console-log-parsers:
      #      - "Custom Bash Syntax"
    triggers:
      - pollscm: '*/5 * * * *'

- job:
    name: Jenkins_Display_icons
    description: |
        Display all the available icons for use in jobs
    properties:
      - github:
          url: https://github.com/devops-workflow/jenkins-display-icons/
      - 'custom-icon':
          custom-icon: jenkins.png
    scm:
      - 'github':
          github-repo: jenkins-display-icons
          github-url: https://github.com
          github-org: devops-workflow
    builders:
      - syntax-bash:
      - shell: ./generate-icons-page.sh
    publishers:
      - html-publisher:
          name: "Icons"
          dir: "."
          files: "icons.html"
    triggers:
      - 'files-found-folder':
          cron: "H * * * *"
          path: "$JENKINS_HOME/userContent/customIcon"
          include: "*.png"

# name: Jenkins_Auto_Job_Builder
