
# Jobs for configuring Jenkins itself - Not application build jobs

- job:
    name: Jenkins_Config
    description: |
        <p><b>Copy global Jenkins configurations files from repo and install plugins</b></p>
    node: master
    disabled: true
    properties:
      - github:
          url: https://github.com/devops-workflow/jenkins-config/
      - 'custom-icon':
          custom-icon: jenkins.png
    scm:
      - 'github':
          github-repo: jenkins-config
          github-url: https://github.com
          github-org: devops-workflow
    builders:
      - 'inject-home':
      - syntax-bash:
      - shell: |
            ./update-config.sh
    publishers:
      - 'pragmatic-programmer-tips':
    triggers:
      - pollscm:
          cron: 'H/15 * * * *'
    wrappers:
      - 'build-timeout':
          timeout: 30
      - 'inject-home':
      - timestamps

- job:
    name: Jenkins_DSL
    # TODO: Add url trigger
    description: |
        <p><b>Create all DSL defined Jenkins Views and Jobs</b></p>
    node: master
    properties:
      - github:
          url: https://github.com/devops-workflow/jenkins-dsls/
      - 'custom-icon':
          custom-icon: jenkins.png
      - 'sidebar-dsl':
      - 'sidebar-groovy':
    scm:
      - 'github':
          github-repo: jenkins-dsls
          github-url: https://github.com
          github-org: devops-workflow
    builders:
      - 'dsl-target':
          dsl-target: |
              DSLs/views*.dsl
              DSLs/jobs*.dsl
    publishers:
      - 'pragmatic-programmer-tips':
    triggers:
      - pollscm:
          cron: 'H/20 * * * *'
    wrappers:
      - timestamps

- job:
    name: Jenkins_Job_Builder
    description: |
        Job to build all other jobs with Jenkins Job Builder
    node: python-jjb
    parameters:
      - string:
          name: remote_job_name
          default: "NO-JOB"
          description: "Jenkins job to get job build definition from"
      - choice:
          name: jjb_cache
          choices:
            - use
            - flush
          description: "Can use to flush cache"
      # Add node parameter. Must run on same node as job that called it
      #- label:
      #    name: node
      #    default: master
      #    description: "The node where the job will run"
    properties:
      - github:
          url: https://github.com/devops-workflow/jenkins-job-builder-config/
      - 'custom-icon':
          custom-icon: jenkins.png
      - 'sidebar-jjb':
    scm:
      - 'github':
          github-repo: jenkins-job-builder-config
          github-url: https://github.com
          github-org: devops-workflow
    builders:
      - 'inject-home':
      - syntax-bash:
      - shell: |
            venv=jjb
            jjb_config=${WORKSPACE}/jjb_config
            #. ${HOME}/bin/source-python-virtual-env.sh
            . source-python-virtual-env.sh
            pyenv activate "${venv}"
            # Run Jenkins Job Builder
            . ./python-env.sh
            # Setup JJB config file
            cat <<CONFIG > ${jjb_config}
            [job_builder]
            keep_descriptions=False
            #include_path=.:scripts:~/git/
            include_path=.:${WORKSPACE}/jenkins-job-builder/global/scripts
            recursive=True
            #exclude=.*:manual:./development
            allow_duplicates=False

            [jenkins]
            user=${jenkinsUser}
            password=${jenkinsAPIKey}
            url=${JENKINS_URL}
            query_plugins_info=True
            CONFIG
            ./run-jjb.sh $remote_job_name $jjb_cache ${jjb_config}
      # If job and jjb made changes, trigger calling job
      # 1) if job and find text in console log
      # 2) tee jjb output to file (jjb.log). Grep text in file
      #- conditional-step:
      #    condition-kind: and
      #    condition-operands:
      #        - condition-kind: not
      #          condition-operand:
      #              condition-kind: strings-match
      #              condition-string1: $remote_job_name
      #              condition-string2: "NO-JOB"
      #              condition-case-insensitive: false
      #        #- condition-kind: text-finder (not currently supported by JJB)
      #        - condition-kind: shell
      #          condition-command: "grep -E 'Number of jobs updated:\S+[1-9]' jjb.log"
      #          # Src line: INFO:root:Number of jobs updated: 0
      #    steps:
      #      - trigger-builds:
      #        - project:
      #            - $remote_job_name
      #          current-parameters: false
      #          # make sure it doesn't run jjb again
      #          predefined-parameters:
      #            remote_job_name=$JOB_NAME
      #          block: false
    publishers:
      - 'pragmatic-programmer-tips':
      - claim-build
      # Unknown issue with warnings
      #- warnings:
      #    console-log-parsers:
      #      - "Custom Bash Syntax"
      - trigger-parameterized-builds:
        - project: Jenkins_DSL
          condition: SUCCESS
          trigger-with-no-params: true
    triggers:
      - pollscm:
          cron: 'H/5 * * * *'
    wrappers:
      - 'build-timeout':
          timeout: 30
      - credentials-binding:
          - username-password-separated:
              # TODO: pass in as JJB parameter
              #credential-id: 6036e7ac-ed29-4dab-addb-c027f8bd1819
              credential-id: user-JenkinsAPI
              username: jenkinsUser
              password: jenkinsAPIKey
      - 'inject-home':
      - timestamps

- job:
    name: Jenkins_Icons
    description: |
        Update icons from git repo and display all the available icons for use in jobs
    node: master
    properties:
      - github:
          url: https://github.com/devops-workflow/jenkins-icons/
      - 'custom-icon':
          custom-icon: jenkins.png
      - 'sidebar-icons':
    scm:
      - 'github':
          github-repo: jenkins-icons
          github-url: https://github.com
          github-org: devops-workflow
    builders:
      - syntax-bash:
      - shell: ./update-icons.sh
    publishers:
      - 'pragmatic-programmer-tips':
      - html-publisher:
          name: "Icons"
          dir: "."
          files: "icons.html"
    triggers:
      - pollscm:
          cron: 'H/20 * * * *'
    wrappers:
      - timestamps

# name: Jenkins_Auto_Job_Builder
