
# Jobs for configuring Jenkins itself - Not application build jobs

- job:
    name: Jenkins_DSL
    # TODO: Add url trigger
    description: |
        <p><b>Create all DSL defined Jenkins Views and Jobs</b></p>
    node: master
    properties:
      - github:
          url: https://github.com/devops-workflow/jenkins-dsls/
      - 'custom-icon':
          custom-icon: jenkins.png
      - 'sidebar-dsl':
      - 'sidebar-groovy':
    scm:
      - 'github':
          github-repo: jenkins-dsls
          github-url: https://github.com
          github-org: devops-workflow
    builders:
      - 'dsl-target':
          dsl-target: |
              DSLs/views*.dsl
              DSLs/jobs*.dsl
    triggers:
      - pollscm:
          cron: 'H/20 * * * *'
    wrappers:
      - timestamps

- job:
    name: Jenkins_Job_Builder
    description: |
        Job to build all other jobs with Jenkins Job Builder
    node: master
    parameters:
      - string:
          name: remote_job_name
          default: "NO-JOB"
          description: "Jenkins job to get job build definition from"
      - choice:
          name: jjb_cache
          choices:
            - use
            - flush
          description: "Can use to flush cache"
      # Add node parameter. Must run on same node as job that called it
      #- label:
      #    name: node
      #    default: master
      #    description: "The node where the job will run"
    properties:
      - github:
          url: https://github.com/devops-workflow/jenkins-job-builder-config/
      - 'custom-icon':
          custom-icon: jenkins.png
      - 'sidebar-jjb':
    scm:
      - 'github':
          github-repo: jenkins-job-builder-config
          github-url: https://github.com
          github-org: devops-workflow
    builders:
      - syntax-bash:
      - shell: |
            ./run-jjb.sh $remote_job_name $jjb_cache
      # If job and jjb made changes, trigger calling job
      # 1) if job and find text in console log
      # 2) tee jjb output to file (jjb.log). Grep text in file
      #- conditional-step:
      #    condition-kind: and
      #    condition-operands:
      #        - condition-kind: not
      #          condition-operand:
      #              condition-kind: strings-match
      #              condition-string1: $remote_job_name
      #              condition-string2: "NO-JOB"
      #              condition-case-insensitive: false
      #        #- condition-kind: text-finder (not currently supported by JJB)
      #        - condition-kind: shell
      #          condition-command: "grep -E 'Number of jobs updated:\S+[1-9]' jjb.log"
      #          # Src line: INFO:root:Number of jobs updated: 0
      #    steps:
      #      - trigger-builds:
      #        - project:
      #            - $remote_job_name
      #          current-parameters: false
      #          # make sure it doesn't run jjb again
      #          predefined-parameters:
      #            remote_job_name=$JOB_NAME
      #          block: false
    publishers:
      - claim-build
      # Unknown issue with warnings
      #- warnings:
      #    console-log-parsers:
      #      - "Custom Bash Syntax"
    triggers:
      - pollscm:
          cron: 'H/5 * * * *'
    wrappers:
      - timestamps

- job:
    name: Jenkins_Icons
    description: |
        Update icons from git repo and display all the available icons for use in jobs
    node: master
    properties:
      - github:
          url: https://github.com/devops-workflow/jenkins-icons/
      - 'custom-icon':
          custom-icon: jenkins.png
      - 'sidebar-icons':
    scm:
      - 'github':
          github-repo: jenkins-icons
          github-url: https://github.com
          github-org: devops-workflow
    builders:
      - syntax-bash:
      - shell: ./update-icons.sh
    publishers:
      - html-publisher:
          name: "Icons"
          dir: "."
          files: "icons.html"
    triggers:
      - pollscm:
          cron: 'H/20 * * * *'
    wrappers:
      - timestamps

# name: Jenkins_Auto_Job_Builder
